/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter_RDV_ (void);
GtkWidget* create_modifier_RDV_ (void);
GtkWidget* create_supprimer_RDV (void);
GtkWidget* create_Donneur (void);
