/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajouter_donneur (void)
{
  GtkWidget *ajouter_donneur;
  GtkWidget *fixed1;
  GtkWidget *nom;
  GtkObject *j_adj;
  GtkWidget *j;
  GtkObject *m_adj;
  GtkWidget *m;
  GtkObject *a_adj;
  GtkWidget *a;
  GtkWidget *cin;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label26;
  GtkWidget *ajouter;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *annuler;
  GtkWidget *label27;
  GtkWidget *msg;

  ajouter_donneur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_donneur), _("Ajouter Donneur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajouter_donneur), fixed1);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 176, 24);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  j_adj = gtk_adjustment_new (4, 1, 31, 1, 10, 10);
  j = gtk_spin_button_new (GTK_ADJUSTMENT (j_adj), 1, 0);
  gtk_widget_show (j);
  gtk_fixed_put (GTK_FIXED (fixed1), j, 80, 144);
  gtk_widget_set_size_request (j, 60, 27);

  m_adj = gtk_adjustment_new (5, 1, 12, 1, 10, 10);
  m = gtk_spin_button_new (GTK_ADJUSTMENT (m_adj), 1, 0);
  gtk_widget_show (m);
  gtk_fixed_put (GTK_FIXED (fixed1), m, 208, 144);
  gtk_widget_set_size_request (m, 60, 27);

  a_adj = gtk_adjustment_new (2001, 1900, 2024, 1, 10, 10);
  a = gtk_spin_button_new (GTK_ADJUSTMENT (a_adj), 1, 0);
  gtk_widget_show (a);
  gtk_fixed_put (GTK_FIXED (fixed1), a, 328, 144);
  gtk_widget_set_size_request (a, 60, 27);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed1), cin, 176, 64);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  label3 = gtk_label_new (_("date:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 24, 112);
  gtk_widget_set_size_request (label3, 41, 17);

  label4 = gtk_label_new (_("jour:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 40, 152);
  gtk_widget_set_size_request (label4, 41, 17);

  label5 = gtk_label_new (_("mois:"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 160, 152);
  gtk_widget_set_size_request (label5, 41, 17);

  label6 = gtk_label_new (_("anne\303\251:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 272, 152);
  gtk_widget_set_size_request (label6, 49, 17);

  label26 = gtk_label_new ("");
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed1), label26, 408, 112);
  gtk_widget_set_size_request (label26, 49, 17);

  ajouter = gtk_button_new_with_mnemonic (_("ajouter "));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 104, 192);
  gtk_widget_set_size_request (ajouter, 88, 40);

  label2 = gtk_label_new (_("cin:\n"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 104, 72);
  gtk_widget_set_size_request (label2, 41, 17);

  label1 = gtk_label_new (_("nom du donneur:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 16, 32);
  gtk_widget_set_size_request (label1, 152, 16);

  annuler = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), annuler, 264, 192);
  gtk_widget_set_size_request (annuler, 80, 40);

  label27 = gtk_label_new ("");
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed1), label27, 208, 264);
  gtk_widget_set_size_request (label27, 49, 17);

  msg = gtk_label_new ("");
  gtk_widget_show (msg);
  gtk_fixed_put (GTK_FIXED (fixed1), msg, 160, 240);
  gtk_widget_set_size_request (msg, 144, 24);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_donneur, ajouter_donneur, "ajouter_donneur");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, nom, "nom");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, j, "j");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, m, "m");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, a, "a");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, cin, "cin");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label6, "label6");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label26, "label26");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label1, "label1");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, label27, "label27");
  GLADE_HOOKUP_OBJECT (ajouter_donneur, msg, "msg");

  return ajouter_donneur;
}

GtkWidget*
create_modifier_donneur_ (void)
{
  GtkWidget *modifier_donneur_;
  GtkWidget *fixed2;
  GtkWidget *nom;
  GtkWidget *cin;
  GtkObject *j_adj;
  GtkWidget *j;
  GtkObject *m_adj;
  GtkWidget *m;
  GtkObject *a_adj;
  GtkWidget *a;
  GtkWidget *label21;
  GtkWidget *label8;
  GtkWidget *label7;
  GtkWidget *label10;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *label9;
  GtkWidget *chercher;
  GtkWidget *modifier;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *annuler;
  GtkWidget *msg;

  modifier_donneur_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_donneur_), _("Modifier Donneur"));
  gtk_window_set_position (GTK_WINDOW (modifier_donneur_), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (modifier_donneur_), fixed2);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 168, 72);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed2), cin, 168, 16);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  j_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  j = gtk_spin_button_new (GTK_ADJUSTMENT (j_adj), 1, 0);
  gtk_widget_show (j);
  gtk_fixed_put (GTK_FIXED (fixed2), j, 80, 176);
  gtk_widget_set_size_request (j, 60, 27);

  m_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  m = gtk_spin_button_new (GTK_ADJUSTMENT (m_adj), 1, 0);
  gtk_widget_show (m);
  gtk_fixed_put (GTK_FIXED (fixed2), m, 208, 176);
  gtk_widget_set_size_request (m, 60, 27);

  a_adj = gtk_adjustment_new (2000, 1900, 2024, 1, 10, 10);
  a = gtk_spin_button_new (GTK_ADJUSTMENT (a_adj), 1, 0);
  gtk_widget_show (a);
  gtk_fixed_put (GTK_FIXED (fixed2), a, 344, 176);
  gtk_widget_set_size_request (a, 60, 27);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 392, 120);
  gtk_widget_set_size_request (label21, 49, 17);

  label8 = gtk_label_new (_("cin:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 96, 16);
  gtk_widget_set_size_request (label8, 48, 32);

  label7 = gtk_label_new (_("nom du donneur:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 32, 72);
  gtk_widget_set_size_request (label7, 120, 31);

  label10 = gtk_label_new (_("jour:"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 24, 184);
  gtk_widget_set_size_request (label10, 49, 17);

  label12 = gtk_label_new (_("anne\303\251:"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 288, 184);
  gtk_widget_set_size_request (label12, 49, 17);

  label11 = gtk_label_new (_("mois:"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 152, 184);
  gtk_widget_set_size_request (label11, 56, 16);

  label9 = gtk_label_new (_("Date:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 24, 120);
  gtk_widget_set_size_request (label9, 48, 24);

  chercher = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed2), chercher, 40, 248);
  gtk_widget_set_size_request (chercher, 88, 32);

  modifier = gtk_button_new_with_mnemonic (_("modifier "));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed2), modifier, 168, 248);
  gtk_widget_set_size_request (modifier, 98, 32);

  label22 = gtk_label_new ("");
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 184, 320);
  gtk_widget_set_size_request (label22, 49, 17);

  label23 = gtk_label_new ("");
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 184, 320);
  gtk_widget_set_size_request (label23, 49, 17);

  label24 = gtk_label_new ("");
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 184, 320);
  gtk_widget_set_size_request (label24, 49, 17);

  annuler = gtk_button_new_with_mnemonic (_("annuler "));
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed2), annuler, 296, 248);
  gtk_widget_set_size_request (annuler, 88, 32);

  msg = gtk_label_new ("");
  gtk_widget_show (msg);
  gtk_fixed_put (GTK_FIXED (fixed2), msg, 136, 296);
  gtk_widget_set_size_request (msg, 168, 24);

  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_donneur_, modifier_donneur_, "modifier_donneur_");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, nom, "nom");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, cin, "cin");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, j, "j");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, m, "m");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, a, "a");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label21, "label21");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label8, "label8");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label10, "label10");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label12, "label12");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label11, "label11");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label9, "label9");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label22, "label22");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label23, "label23");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, label24, "label24");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (modifier_donneur_, msg, "msg");

  return modifier_donneur_;
}

GtkWidget*
create_supprimer_donneur (void)
{
  GtkWidget *supprimer_donneur;
  GtkWidget *fixed3;
  GtkWidget *cin;
  GtkWidget *delete;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *annuler;
  GtkWidget *msg;
  GtkWidget *label14;

  supprimer_donneur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer_donneur), _("Supprimer Donneur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (supprimer_donneur), fixed3);

  cin = gtk_entry_new ();
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed3), cin, 144, 80);
  gtk_widget_set_size_request (cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cin), 8226);

  delete = gtk_button_new_with_mnemonic (_("supprimer "));
  gtk_widget_show (delete);
  gtk_fixed_put (GTK_FIXED (fixed3), delete, 64, 152);
  gtk_widget_set_size_request (delete, 96, 32);

  label19 = gtk_label_new ("");
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 168, 248);
  gtk_widget_set_size_request (label19, 49, 17);

  label20 = gtk_label_new ("");
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 328, 120);
  gtk_widget_set_size_request (label20, 49, 17);

  annuler = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed3), annuler, 240, 152);
  gtk_widget_set_size_request (annuler, 88, 32);

  msg = gtk_label_new ("");
  gtk_widget_show (msg);
  gtk_fixed_put (GTK_FIXED (fixed3), msg, 96, 208);
  gtk_widget_set_size_request (msg, 184, 32);

  label14 = gtk_label_new (_("cin:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 64, 80);
  gtk_widget_set_size_request (label14, 57, 25);

  g_signal_connect ((gpointer) delete, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_donneur, supprimer_donneur, "supprimer_donneur");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, cin, "cin");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, delete, "delete");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, label19, "label19");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, label20, "label20");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, msg, "msg");
  GLADE_HOOKUP_OBJECT (supprimer_donneur, label14, "label14");

  return supprimer_donneur;
}

GtkWidget*
create_Donneur (void)
{
  GtkWidget *Donneur;
  GtkWidget *fixed4;
  GtkWidget *treeview;
  GtkWidget *ajouter;
  GtkWidget *modifier;
  GtkWidget *supprimer;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *refresh;
  GtkWidget *label15;

  Donneur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Donneur), _("window1"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Donneur), fixed4);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview, 40, 80);
  gtk_widget_set_size_request (treeview, 392, 224);

  ajouter = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), ajouter, 56, 336);
  gtk_widget_set_size_request (ajouter, 82, 32);

  modifier = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed4), modifier, 192, 336);
  gtk_widget_set_size_request (modifier, 88, 32);

  supprimer = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer, 320, 336);
  gtk_widget_set_size_request (supprimer, 88, 32);

  label16 = gtk_label_new ("");
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 216, 384);
  gtk_widget_set_size_request (label16, 49, 17);

  label17 = gtk_label_new ("");
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 432, 176);
  gtk_widget_set_size_request (label17, 49, 17);

  refresh = gtk_button_new_with_mnemonic (_("Refresh"));
  gtk_widget_show (refresh);
  gtk_fixed_put (GTK_FIXED (fixed4), refresh, 368, 32);
  gtk_widget_set_size_request (refresh, 88, 32);

  label15 = gtk_label_new (_("Gestion Donneur"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 152, 32);
  gtk_widget_set_size_request (label15, 168, 32);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_CENTER);

  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_tv_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_tv_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_tv_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh, "clicked",
                    G_CALLBACK (on_refresh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Donneur, Donneur, "Donneur");
  GLADE_HOOKUP_OBJECT (Donneur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Donneur, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (Donneur, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (Donneur, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (Donneur, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (Donneur, label16, "label16");
  GLADE_HOOKUP_OBJECT (Donneur, label17, "label17");
  GLADE_HOOKUP_OBJECT (Donneur, refresh, "refresh");
  GLADE_HOOKUP_OBJECT (Donneur, label15, "label15");

  return Donneur;
}

