/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajouter_donneur (void);
GtkWidget* create_modifier_donneur_ (void);
GtkWidget* create_supprimer_donneur (void);
GtkWidget* create_Donneur (void);
